name: CI

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

env:
  # Use for multi-branch deployment
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:

  lint_formatting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install --with dev

      - name: Linting code
        run: poetry run ruff check . # INFO
        continue-on-error: true

      - name: Formating code
        run: poetry run ruff format --check . # INFO
        continue-on-error: true


  unit_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install --with dev

      - name: Type checking
        run: poetry run pyright .

      - name: Run automated tests
        run: poetry run coverage run -m pytest tests -v -s

      - name: Generate coverage report
        run: poetry run coverage report -m
